const sampleListings = [
  {
    id: 1,
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment with floor-to-ceiling windows and panoramic skyline views.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    price: 1200,
    location: "New York City",
    country: "United States",
    type: "Loft",
    guests: 2,
    bedrooms: 1,
    rating: 4.9,
    fee: { cleaning: 80, service: 120 },
  },
  {
    id: 2,
    title: "Beachfront Villa with Pool",
    description: "Luxurious beachfront villa featuring a private infinity pool, direct beach access, and stunning ocean views.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80",
    price: 3500,
    location: "Miami Beach",
    country: "United States",
    type: "Villa",
    guests: 8,
    bedrooms: 4,
    rating: 4.95,
    fee: { cleaning: 250, service: 350 },
  },
  {
    id: 3,
    title: "Cozy Cabin in the Mountains",
    description: "Escape to this charming log cabin surrounded by pine trees, with a fireplace and breathtaking mountain views.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&q=80",
    price: 850,
    location: "Aspen",
    country: "United States",
    type: "Cabin",
    guests: 4,
    bedrooms: 2,
    rating: 4.85,
    fee: { cleaning: 100, service: 85 },
  },
  {
    id: 4,
    title: "Luxury Penthouse Suite",
    description: "An extraordinary penthouse with rooftop terrace, private jacuzzi, and 360-degree views of the Las Vegas Strip.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    price: 5000,
    location: "Las Vegas",
    country: "United States",
    type: "Penthouse",
    guests: 6,
    bedrooms: 3,
    rating: 4.92,
    fee: { cleaning: 300, service: 500 },
  },
  {
    id: 5,
    title: "Parisian Studio Near Eiffel Tower",
    description: "Charming Haussmann-style studio with vintage décor, just a 5-minute walk from the iconic Eiffel Tower.",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
    price: 950,
    location: "Paris",
    country: "France",
    type: "Studio",
    guests: 2,
    bedrooms: 1,
    rating: 4.88,
    fee: { cleaning: 60, service: 95 },
  },
  {
    id: 6,
    title: "Tuscan Countryside Farmhouse",
    description: "Rustic stone farmhouse nestled in rolling Tuscan hills, with olive groves, a wine cellar, and private garden.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    price: 2200,
    location: "Tuscany",
    country: "Italy",
    type: "Farmhouse",
    guests: 10,
    bedrooms: 5,
    rating: 4.97,
    fee: { cleaning: 200, service: 220 },
  },
  {
    id: 7,
    title: "Santorini Cave House",
    description: "Iconic whitewashed cave house carved into the volcanic cliffs with a private plunge pool and caldera views.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
    price: 4200,
    location: "Santorini",
    country: "Greece",
    type: "Cave House",
    guests: 2,
    bedrooms: 1,
    rating: 5.0,
    fee: { cleaning: 150, service: 420 },
  },
  {
    id: 8,
    title: "Tokyo Minimalist Apartment",
    description: "Sleek and serene apartment in Shibuya with Japanese minimalist design, tatami room, and city skyline views.",
    image: "https://images.unsplash.com/photo-1523192193543-6e7296d960e4?w=800&q=80",
    price: 1100,
    location: "Tokyo",
    country: "Japan",
    type: "Apartment",
    guests: 3,
    bedrooms: 2,
    rating: 4.9,
    fee: { cleaning: 70, service: 110 },
  },
  {
    id: 9,
    title: "Bali Jungle Retreat",
    description: "Open-air villa surrounded by tropical rainforest, featuring a natural stone pool, rice terrace views, and outdoor bath.",
    image: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=800&q=80",
    price: 1800,
    location: "Ubud",
    country: "Indonesia",
    type: "Villa",
    guests: 4,
    bedrooms: 2,
    rating: 4.93,
    fee: { cleaning: 120, service: 180 },
  },
  {
    id: 10,
    title: "Scottish Highland Castle",
    description: "Stay like royalty in a restored 16th-century castle with turrets, a grand library, and sweeping loch views.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    price: 6500,
    location: "Inverness",
    country: "United Kingdom",
    type: "Castle",
    guests: 12,
    bedrooms: 6,
    rating: 4.98,
    fee: { cleaning: 400, service: 650 },
  },
  {
    id: 11,
    title: "Overwater Bungalow",
    description: "Exclusive overwater bungalow with a glass floor, direct lagoon access, and spectacular sunset views over the Indian Ocean.",
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&q=80",
    price: 7800,
    location: "Maldives",
    country: "Maldives",
    type: "Bungalow",
    guests: 2,
    bedrooms: 1,
    rating: 5.0,
    fee: { cleaning: 200, service: 780 },
  },
  {
    id: 12,
    title: "Brooklyn Brownstone Townhouse",
    description: "Beautiful 19th-century brownstone in Park Slope with a private garden, exposed brick, and original hardwood floors.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    price: 2800,
    location: "Brooklyn",
    country: "United States",
    type: "Townhouse",
    guests: 6,
    bedrooms: 3,
    rating: 4.87,
    fee: { cleaning: 180, service: 280 },
  },
  {
    id: 13,
    title: "Dubai Marina Skyscraper Suite",
    description: "Ultra-luxe suite on the 55th floor of a glass skyscraper with panoramic marina views, private butler, and spa access.",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    price: 4500,
    location: "Dubai",
    country: "UAE",
    type: "Suite",
    guests: 4,
    bedrooms: 2,
    rating: 4.95,
    fee: { cleaning: 250, service: 450 },
  },
  {
    id: 14,
    title: "Amsterdam Canal Houseboat",
    description: "Unique floating houseboat moored on the Prinsengracht canal with cozy interiors, a sun deck, and city views.",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
    price: 1400,
    location: "Amsterdam",
    country: "Netherlands",
    type: "Houseboat",
    guests: 3,
    bedrooms: 2,
    rating: 4.82,
    fee: { cleaning: 90, service: 140 },
  },
  {
    id: 15,
    title: "Safari Treehouse Lodge",
    description: "Elevated treehouse in the Kenyan savannah, open to the wilderness with a private deck and nightly firepit dining.",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    price: 3200,
    location: "Maasai Mara",
    country: "Kenya",
    type: "Treehouse",
    guests: 2,
    bedrooms: 1,
    rating: 4.99,
    fee: { cleaning: 150, service: 320 },
  },
  {
    id: 16,
    title: "Sydney Harbour View Apartment",
    description: "Stunning modern apartment with floor-to-ceiling windows overlooking the iconic Sydney Opera House and Harbour Bridge.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    price: 2100,
    location: "Sydney",
    country: "Australia",
    type: "Apartment",
    guests: 4,
    bedrooms: 2,
    rating: 4.91,
    fee: { cleaning: 130, service: 210 },
  },
  {
    id: 17,
    title: "Moroccan Riad in the Medina",
    description: "Authentic 17th-century riad with a mosaic courtyard fountain, rooftop terrace, and traditional Moroccan furnishings.",
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
    price: 1600,
    location: "Marrakech",
    country: "Morocco",
    type: "Riad",
    guests: 6,
    bedrooms: 3,
    rating: 4.94,
    fee: { cleaning: 100, service: 160 },
  },
  {
    id: 18,
    title: "Canadian Lakeside Cottage",
    description: "Peaceful cedar cottage on a private lake with a dock, canoe, fire pit, and stunning fall foliage surroundings.",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80",
    price: 1300,
    location: "Muskoka",
    country: "Canada",
    type: "Cottage",
    guests: 6,
    bedrooms: 3,
    rating: 4.86,
    fee: { cleaning: 110, service: 130 },
  },
  {
    id: 19,
    title: "Barcelona Gothic Quarter Flat",
    description: "Elegant flat in a 15th-century building with arched ceilings, mosaic tiles, and a wrought-iron balcony overlooking a cobblestone plaza.",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80",
    price: 1050,
    location: "Barcelona",
    country: "Spain",
    type: "Apartment",
    guests: 4,
    bedrooms: 2,
    rating: 4.89,
    fee: { cleaning: 65, service: 105 },
  },
  {
    id: 20,
    title: "Icelandic Glass Cabin",
    description: "Futuristic glass-walled cabin in the Icelandic wilderness, perfectly positioned for Northern Lights viewing with a hot tub.",
    image: "https://images.unsplash.com/photo-1520769669658-f07657f5a307?w=800&q=80",
    price: 3800,
    location: "Reykjavik",
    country: "Iceland",
    type: "Cabin",
    guests: 2,
    bedrooms: 1,
    rating: 4.97,
    fee: { cleaning: 180, service: 380 },
  },
  {
    id: 21,
    title: "Rio Carnival Penthouse",
    description: "Vibrant penthouse in Ipanema with a rooftop pool, outdoor bar, and sweeping views of Copacabana Beach and Sugarloaf Mountain.",
    image: "https://images.unsplash.com/photo-1544164559-2e64cded1680?w=800&q=80",
    price: 2600,
    location: "Rio de Janeiro",
    country: "Brazil",
    type: "Penthouse",
    guests: 6,
    bedrooms: 3,
    rating: 4.88,
    fee: { cleaning: 170, service: 260 },
  },
  {
    id: 22,
    title: "Kyoto Traditional Machiya",
    description: "Lovingly restored 100-year-old wooden townhouse (machiya) in the Gion district with a zen garden and tea ceremony room.",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    price: 1700,
    location: "Kyoto",
    country: "Japan",
    type: "Townhouse",
    guests: 4,
    bedrooms: 2,
    rating: 4.96,
    fee: { cleaning: 100, service: 170 },
  },
  {
    id: 23,
    title: "Amalfi Coast Clifftop Villa",
    description: "Dramatic villa perched on the Amalfi cliffs with a terraced infinity pool, lemon grove, and sweeping Mediterranean views.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=800&q=80",
    price: 5500,
    location: "Positano",
    country: "Italy",
    type: "Villa",
    guests: 8,
    bedrooms: 4,
    rating: 4.99,
    fee: { cleaning: 320, service: 550 },
  },
  {
    id: 24,
    title: "Cape Town Cliffside Retreat",
    description: "Contemporary retreat clinging to the slopes of Table Mountain with wraparound decks, ocean views, and a heated lap pool.",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    price: 2900,
    location: "Cape Town",
    country: "South Africa",
    type: "House",
    guests: 6,
    bedrooms: 3,
    rating: 4.93,
    fee: { cleaning: 190, service: 290 },
  },
  {
    id: 25,
    title: "Norwegian Fjord Cabin",
    description: "Remote wooden cabin on the edge of a fjord accessible only by boat, with a private sauna, kayaks, and midnight sun.",
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
    price: 2400,
    location: "Flåm",
    country: "Norway",
    type: "Cabin",
    guests: 4,
    bedrooms: 2,
    rating: 4.98,
    fee: { cleaning: 160, service: 240 },
  },
  {
    id: 26,
    title: "Singapore Smart Home Tower",
    description: "Cutting-edge smart home in a supertree tower with automated everything, rooftop garden, and panoramic Marina Bay views.",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    price: 3300,
    location: "Singapore",
    country: "Singapore",
    type: "Apartment",
    guests: 4,
    bedrooms: 2,
    rating: 4.91,
    fee: { cleaning: 200, service: 330 },
  },
  {
    id: 27,
    title: "Peruvian Andean Eco-Lodge",
    description: "Off-grid eco-lodge at 3,800m altitude with panoramic Andes views, llama encounters, and guided Machu Picchu excursions.",
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80",
    price: 1900,
    location: "Sacred Valley",
    country: "Peru",
    type: "Lodge",
    guests: 4,
    bedrooms: 2,
    rating: 4.94,
    fee: { cleaning: 120, service: 190 },
  },
  {
    id: 28,
    title: "Manhattan Micro-Loft",
    description: "Ingeniously designed micro-loft in SoHo with smart storage, convertible furniture, and stylish industrial finishes.",
    image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
    price: 900,
    location: "New York City",
    country: "United States",
    type: "Loft",
    guests: 2,
    bedrooms: 1,
    rating: 4.80,
    fee: { cleaning: 55, service: 90 },
  },
  {
    id: 29,
    title: "Maldivian Private Island",
    description: "Your very own private island experience — a luxury resort villa with personal chef, speedboat, and endless turquoise ocean.",
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
    price: 15000,
    location: "North Malé Atoll",
    country: "Maldives",
    type: "Private Island",
    guests: 6,
    bedrooms: 3,
    rating: 5.0,
    fee: { cleaning: 500, service: 1500 },
  },
  {
    id: 30,
    title: "Vienna Art Nouveau Apartment",
    description: "Grand Belle Époque apartment in the Ringstrasse district adorned with original Jugendstil frescoes, marble floors, and gilded ceilings.",
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80",
    price: 1800,
    location: "Vienna",
    country: "Austria",
    type: "Apartment",
    guests: 5,
    bedrooms: 3,
    rating: 4.96,
    fee: { cleaning: 115, service: 180 },
  },
];

module.exports = {data: sampleListings};